//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibbed.MassEffect3.SaveEdit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gibbed.MassEffect3.SaveEdit.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot open Xbox 360 CON files with the save editor..
        /// </summary>
        internal static string Editor_CannotLoadXbox360CONFile {
            get {
                return ResourceManager.GetString("Editor_CannotLoadXbox360CONFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse id..
        /// </summary>
        internal static string Editor_FailedToParseId {
            get {
                return ResourceManager.GetString("Editor_FailedToParseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse value..
        /// </summary>
        internal static string Editor_FailedToParseValue {
            get {
                return ResourceManager.GetString("Editor_FailedToParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That file does not appear to be an exported head morph..
        /// </summary>
        internal static string Editor_HeadMorphInvalid {
            get {
                return ResourceManager.GetString("Editor_HeadMorphInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The head morph you are importing has a different version ({0}) than your current save file ({1}).
        ///
        ///Import anyway?.
        /// </summary>
        internal static string Editor_HeadMorphVersionMaybeIncompatible {
            get {
                return ResourceManager.GetString("Editor_HeadMorphVersionMaybeIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported head morph export version..
        /// </summary>
        internal static string Editor_HeadMorphVersionUnsupported {
            get {
                return ResourceManager.GetString("Editor_HeadMorphVersionUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active save..
        /// </summary>
        internal static string Editor_NoActiveSave {
            get {
                return ResourceManager.GetString("Editor_NoActiveSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This save does not have a non-default head morph..
        /// </summary>
        internal static string Editor_NoHeadMorph {
            get {
                return ResourceManager.GetString("Editor_NoHeadMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool {0} is set to {1}.
        /// </summary>
        internal static string Editor_PlotManualLogBoolGet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogBoolGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool {0} set to {1} (was {2}).
        /// </summary>
        internal static string Editor_PlotManualLogBoolSet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogBoolSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float {0} is set to {1}.
        /// </summary>
        internal static string Editor_PlotManualLogFloatGet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogFloatGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float {0} set to {1} (was {2}).
        /// </summary>
        internal static string Editor_PlotManualLogFloatSet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogFloatSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int {0} is set to {1}.
        /// </summary>
        internal static string Editor_PlotManualLogIntGet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogIntGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int {0} set to {1} (was {2}).
        /// </summary>
        internal static string Editor_PlotManualLogIntSet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogIntSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception trying to read the save file.
        ///Please report this message to Rick (ctrl+C to copy this dialog) and include a copy of the save file you tried to load.
        ///
        ///{0}.
        /// </summary>
        internal static string Editor_SaveReadException {
            get {
                return ResourceManager.GetString("Editor_SaveReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should never happen..
        /// </summary>
        internal static string Editor_ThisShouldNeverHappen {
            get {
                return ResourceManager.GetString("Editor_ThisShouldNeverHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this career?.
        /// </summary>
        internal static string SavePicker_DeleteCareerConfirmation {
            get {
                return ResourceManager.GetString("SavePicker_DeleteCareerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error removing the directory:
        ///.
        /// </summary>
        internal static string SavePicker_DeleteCareerIOException {
            get {
                return ResourceManager.GetString("SavePicker_DeleteCareerIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this save?.
        /// </summary>
        internal static string SavePicker_DeleteSaveConfirmation {
            get {
                return ResourceManager.GetString("SavePicker_DeleteSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error removing the file:
        ///.
        /// </summary>
        internal static string SavePicker_DeleteSaveIOException {
            get {
                return ResourceManager.GetString("SavePicker_DeleteSaveIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new career).
        /// </summary>
        internal static string SavePIcker_NewCareerLabel {
            get {
                return ResourceManager.GetString("SavePIcker_NewCareerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new save).
        /// </summary>
        internal static string SavePicker_NewSaveLabel {
            get {
                return ResourceManager.GetString("SavePicker_NewSaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite this save file?.
        /// </summary>
        internal static string SavePicker_SaveOverwriteConfirmation {
            get {
                return ResourceManager.GetString("SavePicker_SaveOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
